#!/bin/bash

# Bandwidth, pageable, (CPUTiming) >> ./results/w_pageable.txt
./bin/dataTransferExp --exp=bw --memory=pageable >> ./results/bw_pageable.txt

# Bandwidth, pinned, wc=false, GPUTiming >> ./results/bw_pinned.txt
./bin/dataTransferExp --exp=bw --memory=pinned >> ./results/bw_pinned.txt

# Bandwidth, pinned, wc=true, GPUTiming >> ./results/bw_pinned_wc.txt
./bin/dataTransferExp --exp=bw --memory=pinned --wc >> ./results/bw_pinned_wc.txt


