#!/bin/bash

# Assume each pixel is a char (1 byte)
./bin/imageTest --char >> ./results/time_1byte.txt

# Assume each pixel is a short (2 bytes)
./bin/imageTest --short >> ./results/time_2bytes.txt

# Assume each pixel is an int (4 bytes)
./bin/imageTest --int >> ./results/time_4bytes.txt

# Assume each pixel is a long long (8 bytes)
./bin/imageTest --long >> ./results/time_8bytes.txt
